project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Statistical Rethinking colearning 2024 - Bella"

  sidebar:
    contents: auto
     
format:
  html:
    theme:
      light: minty
      dark: slate
    toc: true