project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Statistical Rethinking colearning 2023 - Bella"

  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "Homework"
        href: homework/homework-listing.qmd
        contents:
          - href: homework/homework-01.qmd
            text: Homework 01
      - section: "Notes"
        href: notes/notes-listing.qmd
        contents:
          - href: notes/notes-01.qmd
            text: Lecture 01
          - href: notes/notes-02.qmd
            text: Lecture 02
          - href: notes/notes-03.qmd
            text: Lecture 03

format:
  html:
    theme:
      dark: slate
      light: minty
    toc: true