project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - "_targets.R"

website:
  title: "Statistical Rethinking colearning 2024 - Bella"
  repo-url: https://github.com/robitalec/statistical-rethinking-colearning-2024
  repo-actions: [edit, issue]

  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - section: Notes
        contents:
          - auto: "notes/*"
      - section: Homework
        contents:
          - auto: "homework/*"
    tools:
      - icon: github
        href: https://github.com/robitalec/statistical-rethinking-colearning-2024

     
format:
  html:
    theme:
      light: minty
      dark: slate
    toc: true